openapi: 3.1.1
info:
  title: Entitlement
  version: 2.0.0
  description: A contractually granted, policy-governed right that allows a specific
    party to access, use, or claim a defined economic resource within stated scope
    and validity constraints. It represents the enforceable permission created by
    an order, independent of the credential used to exercise it.
  license:
    name: CC-BY-NC-SA 4.0 International
  contact:
    name: Beckn Labs
    url: https://beckn.io
components:
  schemas:
    Entitlement:
      x-iri: https://schema.nfh.global/Entitlement/v2.0
      description: A contractually granted, policy-governed right that allows a specific
        party to access, use, or claim a defined economic resource within stated scope
        and validity constraints. It represents the enforceable permission created
        by an order, independent of the credential used to exercise it.
      title: Entitlement
      type: object
      properties:
        id:
          description: A unique identifier for this entitlement within the entitlement
            provider's namespace
          type: string
        resource:
          description: The resource being availed or accessed against this entitlement
          $ref: https://schema.nfh.global/ContractItem/v2.0/attributes.yaml#/components/schemas/ContractItem
        descriptor:
          description: Human-readable information regarding the entitlement like QR-code
            images, attached documents containing terms and conditions, video or audio
            files instructing the user on how to use the entitlement
          $ref: https://schema.nfh.global/Descriptor/v2.1/attributes.yaml#/components/schemas/Descriptor
        credentials:
          type: array
          items:
            $ref: https://schema.nfh.global/Descriptor/v2.1/attributes.yaml#/components/schemas/Descriptor
      additionalProperties: true
      required:
      - id
      - descriptor
      x-tags:
      - common
