openapi: 3.1.1
info:
  title: Eligibility
  version: 2.0.0
  description: Schema definition for Eligibility in the Beckn Protocol v2.0.1
  license:
    name: CC-BY-NC-SA 4.0 International
  contact:
    name: Beckn Labs
    url: https://beckn.io
components:
  schemas:
    Eligibility:
      x-iri: https://schema.nfh.global/Eligibility/v2.0
      description: Schema definition for Eligibility in the Beckn Protocol v2.0.1
      title: Eligibility
      x-tags:
      - common
      type: object
      properties:
        eligibleQuantity:
          type: object
          properties:
            max:
              type: number
            min:
              type: number
        eligibleRegion:
          type: string
      x-jsonld:
        '@id': schema:DefinedRegion|schema:QuantitativeValue
      additionalProperties: false
