openapi: 3.1.1
info:
  title: AckNoCallback
  version: 2.0.0
  description: "Container schemas fetched from beckn.yaml. This cannot be extended as it is a reserved schema in beckn protocol. Any additional properties added to this schema can only be made using its *Attributes property"
  license:
    name: CC-BY-NC-SA 4.0 International
  contact:
    name: Beckn Labs
    url: https://beckn.io
components:
  schemas:
    AckNoCallback:
      x-iri: https://schema.nfh.global/AckNoCallback/v2.0
      description: Request received but no callback will follow (e.g. agents not found,
        inventory unavailable, provider closed, context.try preview complete).
      allOf:
      - $ref: https://schema.nfh.global/Ack/v2.0/attributes.yaml#/components/schemas/Ack
      - type: object
        properties:
          error:
            $ref: https://schema.nfh.global/Error/v2.0/attributes.yaml#/components/schemas/Error
      - required:
        - status
        - signature
        - error
