openapi: 3.1.1
info:
  title: MediaSearch
  version: 2.0.0
  description: "Container schemas fetched from beckn.yaml. This cannot be extended as it is a reserved schema in beckn protocol. Any additional properties added to this schema can only be made using its *Attributes property"
  license:
    name: CC-BY-NC-SA 4.0 International
  contact:
    name: Beckn Labs
    url: https://beckn.io
components:
  schemas:
    MediaSearch:
      x-iri: https://schema.nfh.global/MediaSearch/v2.0
      type: object
      properties:
        media:
          type: array
          items:
            $ref: https://schema.nfh.global/MediaInput/v2.0/attributes.yaml#/components/schemas/MediaInput
        options:
          $ref: https://schema.nfh.global/MediaSearchOptions/v2.0/attributes.yaml#/components/schemas/MediaSearchOptions
      additionalProperties: false
