openapi: 3.1.1
info:
  title: Support
  version: 2.0.0
  description: "Container schemas fetched from beckn.yaml. This cannot be extended as it is a reserved schema in beckn protocol. Any additional properties added to this schema can only be made using its *Attributes property"
  license:
    name: CC-BY-NC-SA 4.0 International
  contact:
    name: Beckn Labs
    url: https://beckn.io
components:
  schemas:
    Support:
      x-iri: https://schema.nfh.global/Support/v2.0
      description: Describes a support session info
      title: Support
      type: object
      properties:
        orderId:
          description: The order against which support is required
          type: string
        descriptor:
          description: A description of the nature of support needed
          $ref: https://schema.nfh.global/Descriptor/v2.1/attributes.yaml#/components/schemas/Descriptor
        channels:
          description: Available support channels described in individual linked data
            JSON objects
          type: array
          minItems: 1
          items:
            $ref: https://schema.nfh.global/Attributes/v2.0/attributes.yaml#/components/schemas/Attributes
      additionalProperties: false
