openapi: 3.1.1
info:
  title: PaymentTerms
  version: 2.0.0
  description: Schema definition for PaymentTerms in the Beckn Protocol v2.0.1
  license:
    name: CC-BY-NC-SA 4.0 International
  contact:
    name: Beckn Labs
    url: https://beckn.io
components:
  schemas:
    PaymentTerms:
      x-iri: https://schema.nfh.global/PaymentTerms/v2.0
      description: Schema definition for PaymentTerms in the Beckn Protocol v2.0.1
      title: PaymentTerms
      x-tags:
      - common
      type: object
      properties:
        collectedBy:
          description: Describes the entity that first collects the payment from the
            consumer. This is the actor who is responsible to initiate the settlement
            process as per the terms described in the settlementTerms property.
          type: string
          enum:
          - BAP
          - BPP
          - ESCROW_AGENT
        checkoutAt:
          $ref: https://schema.nfh.global/CheckoutTerminal/v2.0/attributes.yaml#/components/schemas/CheckoutTerminal
        settlementTerms:
          type: array
          items:
            $ref: https://schema.nfh.global/SettlementTerm/v2.0/attributes.yaml#/components/schemas/SettlementTerm
        checkoutTrigger:
          description: The stage in the order lifecycle when the checkout should be
            triggered
          $ref: https://schema.nfh.global/PaymentTrigger/v2.0/attributes.yaml#/components/schemas/PaymentTrigger
        paymentTermsAttributes:
          description: 'Rail-specific attribute pack (e.g., UPI: VPA/UTR; CARD: token/3DS;
            BNPL: plan/schedule)'
          $ref: https://schema.nfh.global/Attributes/v2.0/attributes.yaml#/components/schemas/Attributes
      additionalProperties: false
