openapi: 3.1.1
info:
  title: PriceSpecification
  version: 2.1.0
  description: Schema definition for PriceSpecification in the Beckn Protocol v2.0.1
  license:
    name: CC-BY-NC-SA 4.0 International
  contact:
    name: Beckn Labs
    url: https://beckn.io
components:
  schemas:
    PriceSpecification:
      x-iri: https://schema.nfh.global/PriceSpecification/v2.1
      description: Schema definition for PriceSpecification in the Beckn Protocol v2.0.1
      title: PriceSpecification
      type: object
      additionalProperties: true
      properties:
        currency:
          type: string
          description: ISO 4217 code
        value:
          type: number
          description: Total value for this price specification
        applicableQuantity:
          $ref: https://schema.nfh.global/Quantity/v2.0/attributes.yaml#/components/schemas/Quantity
          x-jsonld:
            '@id': schema:eligibleQuantity
        components:
          type: array
          description: Optional components (tax, shipping, discount, fee, surcharge)
          items:
            type: object
            properties:
              type:
                type: string
                enum:
                - UNIT
                - TAX
                - DELIVERY
                - DISCOUNT
                - FEE
                - SURCHARGE
              value:
                type: number
              currency:
                type: string
              description:
                type: string
      x-jsonld:
        '@id': schema:PriceSpecification
      x-tags:
      - common
