openapi: 3.1.1
info:
  title: SupportTicket
  version: 2.0.0
  description: A support ticket raised against an order
  license:
    name: CC-BY-NC-SA 4.0 International
  contact:
    name: Beckn Labs
    url: https://beckn.io
components:
  schemas:
    SupportTicket:
      x-iri: https://schema.nfh.global/SupportTicket/v2.0
      description: A support ticket raised against an order
      title: SupportTicket
      x-tags:
      - common
      type: object
      properties:
        id:
          description: Ticket ID
          type: string
        supportTicketAttributes:
          $ref: https://schema.nfh.global/Attributes/v2.0/attributes.yaml#/components/schemas/Attributes
      additionalProperties: false
