openapi: 3.1.1
info:
  title: TrackAction
  version: 2.0.0
  description: Minimal schema.org TrackAction for clickable tracking.
  license:
    name: CC-BY-NC-SA 4.0 International
  contact:
    name: Beckn Labs
    url: https://beckn.io
components:
  schemas:
    TrackAction:
      x-iri: https://schema.nfh.global/TrackAction/v2.0
      description: Minimal schema.org TrackAction for clickable tracking.
      title: TrackAction
      type: object
      properties:
        id:
          type: string
          description: Tracking action identifier
          x-jsonld:
            '@id': schema:identifier
        url:
          type: string
          format: uri
          description: Tracking page URL
          x-jsonld:
            '@id': schema:url
      additionalProperties: true
      x-jsonld:
        '@type': schema:TrackAction
