openapi: 3.1.1
info:
  title: TimePeriod
  version: 2.1.0
  description: "Container schemas fetched from beckn.yaml. This cannot be extended as it is a reserved schema in beckn protocol. Any additional properties added to this schema can only be made using its *Attributes property"
  license:
    name: CC-BY-NC-SA 4.0 International
  contact:
    name: Beckn Labs
    url: https://beckn.io
components:
  schemas:
    TimePeriod:
      x-iri: https://schema.nfh.global/TimePeriod/v2.1
      description: 'Time window with date-time precision for availability/validity


        This schema is part of the Long Term Support of Beckn Protocol V2.0 API specification and MUST NOT be extended. Any domain-specific extension must use the property of this schema which is of type Attribute.'
      title: TimePeriod
      x-tags:
      - common
      type: object
      properties:
        startDate:
          description: Start instant (inclusive)
          type: string
          format: date-time
          example: '2025-01-27T09:00:00Z'
        endDate:
          description: End instant (exclusive or inclusive per domain semantics)
          type: string
          format: date-time
          example: '2025-12-31T23:59:59Z'
        startTime:
          description: Start time of the time period
          type: string
          format: time
          example: 09:00:00
        endTime:
          description: End time of the time period
          type: string
          format: time
          example: '22:00:00'
      anyOf:
      - required:
        - startDate
      - required:
        - endDate
      - required:
        - startTime
        - endTime
      additionalProperties: false
      x-lts: true
