openapi: 3.1.1
info:
  title: Organization
  version: 2.0.0
  description: An organization such as a company, non-profit, or governmental institution.
    Modeled after schema.org/Organization.
  license:
    name: CC-BY-NC-SA 4.0 International
  contact:
    name: Beckn Labs
    url: https://beckn.io
components:
  schemas:
    Organization:
      x-iri: https://schema.nfh.global/Organization/v2.0
      description: An organization such as a company, non-profit, or governmental
        institution. Modeled after schema.org/Organization.
      title: Organization
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the organization
          x-jsonld:
            '@id': schema:identifier
        name:
          type: string
          description: Name of the organization
          x-jsonld:
            '@id': schema:name
        email:
          type: string
          format: email
          description: Email address
          x-jsonld:
            '@id': schema:email
        telephone:
          type: string
          description: Telephone number
          x-jsonld:
            '@id': schema:telephone
        address:
          description: Physical address
          oneOf:
          - type: string
          - $ref: https://schema.nfh.global/Address/v2.0/attributes.yaml#/components/schemas/Address
          x-jsonld:
            '@id': schema:address
        credentials:
          type: array
          description: Credentials held by the organization
          items:
            $ref: https://schema.nfh.global/Credential/v2.0/attributes.yaml#/components/schemas/Credential
          x-jsonld:
            '@id': schema:hasCredential
        skills:
          type: array
          description: Skills or capabilities of the organization
          items:
            $ref: https://schema.nfh.global/Skill/v2.0/attributes.yaml#/components/schemas/Skill
          x-jsonld:
            '@id': schema:hasSkill
        organizationAttributes:
          description: Extensible attribute pack for jurisdictional or domain-specific
            organization properties
          $ref: https://schema.nfh.global/Attributes/v2.0/attributes.yaml#/components/schemas/Attributes
      required:
      - id
      additionalProperties: false
      x-tags:
      - common
