openapi: 3.1.1
info:
  title: Location
  version: 2.0.0
  description: "Container schemas fetched from beckn.yaml. This cannot be extended as it is a reserved schema in beckn protocol. Any additional properties added to this schema can only be made using its *Attributes property"
  license:
    name: CC-BY-NC-SA 4.0 International
  contact:
    name: Beckn Labs
    url: https://beckn.io
components:
  schemas:
    Location:
      x-iri: https://schema.nfh.global/Location/v2.0
      description: 'A place represented by GeoJSON geometry and optional address.

        Source: main/schema/core/v2/attributes.yaml#Location'
      type: object
      required:
      - geo
      additionalProperties: false
      properties:
        geo:
          $ref: https://schema.nfh.global/GeoJSONGeometry/v2.0/attributes.yaml#/components/schemas/GeoJSONGeometry
        address:
          $ref: https://schema.nfh.global/Address/v2.0/attributes.yaml#/components/schemas/Address
