openapi: 3.1.1
info:
  title: AsyncError
  version: 2.0.0
  description: "Container schemas fetched from beckn.yaml. This cannot be extended as it is a reserved schema in beckn protocol. Any additional properties added to this schema can only be made using its *Attributes property"
  license:
    name: CC-BY-NC-SA 4.0 International
  contact:
    name: Beckn Labs
    url: https://beckn.io
components:
  schemas:
    AsyncError:
      x-iri: https://schema.nfh.global/AsyncError/v2.0
      title: Asynchronous Error
      description: Error returned asynchronously during a callback. Wraps the base
        `Error` schema with JSON-LD type annotations to allow linked-data processing.
      allOf:
      - $ref: https://schema.nfh.global/Error/v2.0/attributes.yaml#/components/schemas/Error
      - type: object
        properties: {}
        additionalProperties: true
