openapi: 3.1.1
info:
  title: Policy
  version: 2.0.0
  description: Schema definition for Policy in the Beckn Protocol v2.0.1
  license:
    name: CC-BY-NC-SA 4.0 International
  contact:
    name: Beckn Labs
    url: https://beckn.io
components:
  schemas:
    Policy:
      x-iri: https://schema.nfh.global/Policy/v2.0
      description: Schema definition for Policy in the Beckn Protocol v2.0.1
      title: Policy
      type: object
      properties:
        descriptor:
          description: Validity window for this policy version
          $ref: https://schema.nfh.global/Descriptor/v2.1/attributes.yaml#/components/schemas/Descriptor
        id:
          description: Identifier for the policy
          type: string
        policyType:
          description: Type/kind of policy (extensible term)
          type: string
        validity:
          description: Validity window for this policy version
          $ref: https://schema.nfh.global/TimePeriod/v2.1/attributes.yaml#/components/schemas/TimePeriod
        policyAttributes:
          $ref: https://schema.nfh.global/Attributes/v2.0/attributes.yaml#/components/schemas/Attributes
      required:
      - id
      - descriptor
      additionalProperties: false
      x-tags:
      - common
