openapi: 3.1.1
info:
  title: FulfillmentAgent
  version: 2.0.0
  description: The entity directly involved in fulfilling the order. It could be a
    person, an organization, a machine, a software application, or an AI Agent.
  license:
    name: CC-BY-NC-SA 4.0 International
  contact:
    name: Beckn Labs
    url: https://beckn.io
components:
  schemas:
    FulfillmentAgent:
      x-iri: https://schema.nfh.global/FulfillmentAgent/v2.0
      description: The entity directly involved in fulfilling the order. It could
        be a person, an organization, a machine, a software application, or an AI
        Agent.
      title: FulfillmentAgent
      allOf:
      - type: object
        additionalProperties: false
        properties:
          agentAttributes:
            description: "Attribute Pack reference for richer identity: # agent/identity.v1\
              \ (contact details: email, phone, address) # agent/org-ids.v1 (LEI,\
              \ GSTIN, ISIN, CUSIP\u2026) # consumer/kyc.v1 (jurisdictional compliance\
              \ fields) # (accessibility needs, etc.)\n"
            $ref: https://schema.nfh.global/Attributes/v2.0/attributes.yaml#/components/schemas/Attributes
        required: []
      - oneOf:
        - type: object
          additionalProperties: false
          properties:
            person:
              $ref: https://schema.nfh.global/Person/v2.0/attributes.yaml#/components/schemas/Person
          required:
          - person
        - type: object
          additionalProperties: false
          properties:
            organization:
              $ref: https://schema.nfh.global/Organization/v2.0/attributes.yaml#/components/schemas/Organization
          required:
          - organization
      x-tags:
      - common
