openapi: 3.1.1
info:
  title: Resource
  version: 2.0.0
  description: "Container schemas fetched from beckn.yaml. This cannot be extended as it is a reserved schema in beckn protocol. Any additional properties added to this schema can only be made using its *Attributes property"
  license:
    name: CC-BY-NC-SA 4.0 International
  contact:
    name: Beckn Labs
    url: https://beckn.io
components:
  schemas:
    Resource:
      x-iri: https://schema.nfh.global/Resource/v2.0
      type: object
      description: "A minimal, domain-neutral abstraction representing any discoverable, \
        referenceable, or committable unit of value, capability, service, entitlement,\
        \ or asset within the network.  Examples: - A retail product SKU, a mobility\
        \ ride, a job role, a carbon credit unit,  a dataset/API entitlement, a training\
        \ course, a clinic service slot.  Designed for composability through `resourceAttributes`\
        \ where domain packs can plug in their specific fields without changing the\
        \ core."
      required:
      - id
      properties:
        id:
          type: string
          description: Globally unique identifier of the resource.
        descriptor:
          $ref: https://schema.nfh.global/Descriptor/v2.1/attributes.yaml#/components/schemas/Descriptor
        resourceAttributes:
          description: All the properties of a resource that describe its value, its
            terms of usage, fulfillment, and consideration
          $ref: https://schema.nfh.global/Attributes/v2.0/attributes.yaml#/components/schemas/Attributes
