openapi: 3.1.1
info:
  title: DisplayedRating
  version: 2.0.0
  description: Schema definition for DisplayedRating in the Beckn Protocol v2.0.1
  license:
    name: CC-BY-NC-SA 4.0 International
  contact:
    name: Beckn Labs
    url: https://beckn.io
components:
  schemas:
    DisplayedRating:
      x-iri: https://schema.nfh.global/DisplayedRating/v2.0
      description: Schema definition for DisplayedRating in the Beckn Protocol v2.0.1
      title: DisplayedRating
      x-tags:
      - common
      type: object
      properties:
        '@type':
          description: Type of the rating
          type: string
          enum:
          - Rating
          example: Rating
        ratingCount:
          description: Number of ratings
          type: integer
          minimum: 0
          example: 1250
        ratingValue:
          description: Rating value (0-5)
          type: number
          minimum: 0
          maximum: 5
          example: 4.8
      required:
      - '@type'
      additionalProperties: false
