openapi: 3.1.1
info:
  title: Attributes
  version: 2.0.0
  description: Container schemas fetched from beckn.yaml. This cannot be extended
    as it is a reserved schema in beckn protocol. Any additional properties added
    to this schema can only be made using its *Attributes property
  license:
    name: CC-BY-NC-SA 4.0 International
  contact:
    name: Beckn Labs
    url: https://beckn.io
components:
  schemas:
    Attributes:
      x-iri: https://schema.nfh.global/Attributes/v2.0
      description: JSON-LD aware container for domain-specific attributes of an Item.
        MUST include @context (URI) and @type (compact or full IRI). Any additional
        properties are allowed and interpreted per the provided JSON-LD context.
      title: Attributes
      type: object
      properties: {}
      required: []
      additionalProperties: true
      x-tags:
      - common
