openapi: 3.1.1
info:
  title: CatalogOnPublishAction
  version: 2.0.0
  description: "Container schemas fetched from beckn.yaml. This cannot be extended as it is a reserved schema in beckn protocol. Any additional properties added to this schema can only be made using its *Attributes property"
  license:
    name: CC-BY-NC-SA 4.0 International
  contact:
    name: Beckn Labs
    url: https://beckn.io
components:
  schemas:
    CatalogOnPublishAction:
      x-iri: https://schema.nfh.global/CatalogOnPublishAction/v2.0
      description: Catalog publish processing results from CDS to BPP.
      type: object
      required:
      - results
      properties:
        results:
          type: array
          description: Per-catalog processing results
          items:
            $ref: https://schema.nfh.global/CatalogProcessingResult/v2.0/attributes.yaml#/components/schemas/CatalogProcessingResult
