openapi: 3.1.1
info:
  title: Quantity
  version: 2.0.0
  description: Schema definition for Quantity in the Beckn Protocol v2.0.1
  license:
    name: CC-BY-NC-SA 4.0 International
  contact:
    name: Beckn Labs
    url: https://beckn.io
components:
  schemas:
    Quantity:
      x-iri: https://schema.nfh.global/Quantity/v2.0
      description: Schema definition for Quantity in the Beckn Protocol v2.0.1
      title: Quantity
      type: object
      properties:
        maxQuantity:
          description: Maximum quantity for this price
          type: number
          x-jsonld:
            '@id': schema:Number
          example: 100
        minQuantity:
          description: Minimum quantity for this price
          type: number
          x-jsonld:
            '@id': schema:Number
          example: 1
        unitCode:
          description: Unit code for the quoted price (e.g., KWH, MIN, H, MON)
          type: string
          x-jsonld:
            '@id': schema:unitCode
          example: KWH
        unitQuantity:
          description: Quantity of the unit
          type: number
          x-jsonld:
            '@id': schema:Number
          example: 1
        unitText:
          description: Unit for the quoted price (e.g., kWh, minute, hour, month)
          type: string
          x-jsonld:
            '@id': schema:unitText
          example: kWh
      x-jsonld:
        '@id': schema:QuantitativeValue
      additionalProperties: false
      x-tags:
      - common
