openapi: 3.1.1
info:
  title: Skill
  version: 2.0.0
  description: Schema definition for Skill in the Beckn Protocol v2.0.1
  license:
    name: CC-BY-NC-SA 4.0 International
  contact:
    name: Beckn Labs
    url: https://beckn.io
components:
  schemas:
    Skill:
      x-iri: https://schema.nfh.global/Skill/v2.0
      description: Schema definition for Skill in the Beckn Protocol v2.0.1
      title: Skill
      type: object
      properties:
        category:
          $ref: https://schema.nfh.global/CategoryCode/v2.1/attributes.yaml#/components/schemas/CategoryCode
        descriptor:
          $ref: https://schema.nfh.global/Descriptor/v2.1/attributes.yaml#/components/schemas/Descriptor
        id:
          type: string
      required:
      - id
      - descriptor
      additionalProperties: false
      x-tags:
      - common
