openapi: 3.1.1
info:
  title: Pagination
  version: 2.0.0
  description: "Container schemas fetched from beckn.yaml. This cannot be extended as it is a reserved schema in beckn protocol. Any additional properties added to this schema can only be made using its *Attributes property"
  license:
    name: CC-BY-NC-SA 4.0 International
  contact:
    name: Beckn Labs
    url: https://beckn.io
components:
  schemas:
    Pagination:
      x-iri: https://schema.nfh.global/Pagination/v2.0
      type: object
      description: 'Pagination metadata returned with list responses


        This schema is part of the Long Term Support of Beckn Protocol V2.0 API specification and MUST NOT be extended. Any domain-specific extension must use the property of this schema which is of type Attribute.'
      properties:
        count:
          type: integer
          description: Number of items in this page
        limit:
          type: integer
          description: Page size used in this response
        offset:
          type: integer
          description: Zero-based offset used in this response
      x-lts: true
