openapi: 3.1.1
info:
  title: TrackAction
  version: 2.1.0
  description: "Container schemas fetched from beckn.yaml. This cannot be extended as it is a reserved schema in beckn protocol. Any additional properties added to this schema can only be made using its *Attributes property"
  license:
    name: CC-BY-NC-SA 4.0 International
  contact:
    name: Beckn Labs
    url: https://beckn.io
components:
  schemas:
    TrackAction:
      x-iri: https://schema.nfh.global/TrackAction/v2.1
      type: object
      description: Details required to initiate real-time tracking (if relevant) for
        an ongoing transaction
      additionalProperties: false
      properties:
        tracking:
          $ref: https://schema.nfh.global/Tracking/v2.1/attributes.yaml#/components/schemas/Tracking
      required:
      - tracking
