openapi: 3.1.1
info:
  title: Provider
  version: 2.0.0
  description: Schema definition for Provider in the Beckn Protocol
  license:
    name: CC-BY-NC-SA 4.0 International
  contact:
    name: Beckn Labs
    url: https://beckn.io
components:
  schemas:
    Provider:
      x-iri: https://schema.nfh.global/Provider/v2.0
      description: Schema definition for Provider in the Beckn Protocol
      title: Provider
      type: object
      properties:
        beckn:id:
          type: string
          description: Unique identifier for the provider
          example: tech-store-001
        beckn:descriptor:
          $ref: https://schema.nfh.global/Descriptor/v2.1/attributes.yaml#/components/schemas/Descriptor
        beckn:validity:
          $ref: https://schema.nfh.global/TimePeriod/v2.1/attributes.yaml#/components/schemas/TimePeriod
        beckn:locations:
          type: array
          items:
            $ref: https://schema.nfh.global/Location/v2.0/attributes.yaml#/components/schemas/Location
          description: Physical locations where the provider operates
        beckn:rateable:
          type: boolean
          description: Whether the provider can be rated by customers
          example: true
        beckn:rating:
          $ref: https://schema.nfh.global/Rating/v2.1/attributes.yaml#/components/schemas/Rating
        beckn:providerAttributes:
          $ref: https://schema.nfh.global/Attributes/v2.0/attributes.yaml#/components/schemas/Attributes
      required:
      - beckn:id
      - beckn:descriptor
      additionalProperties: false
