openapi: 3.1.1
info:
  title: Consumer
  version: 2.0.0
  description: Schema definition for Consumer in the Beckn Protocol v2.0.1
  license:
    name: CC-BY-NC-SA 4.0 International
  contact:
    name: Beckn Labs
    url: https://beckn.io
components:
  schemas:
    Consumer:
      x-iri: https://schema.nfh.global/Consumer/v2.0
      description: Schema definition for Consumer in the Beckn Protocol v2.0
      title: Consumer
      type: object
      additionalProperties: false
      properties:
        role:
          description: The functional role of the consumer in the transaction.
          type: string
          x-jsonld:
            '@id': schema:roleName
        consumerAttributes:
          description: "Attribute Pack reference for richer identity: # consumer/identity.v1\
            \ (contact details: email, phone, address) # consumer/org-ids.v1 (LEI,\
            \ GSTIN, ISIN, CUSIP\u2026) # consumer/kyc.v1 (jurisdictional compliance\
            \ fields) # consumer/preferences.v1 (delivery preferences, accessibility\
            \ needs, etc.)"
          $ref: https://schema.nfh.global/Attributes/v2.0/attributes.yaml#/components/schemas/Attributes
        person:
          $ref: https://schema.nfh.global/Person/v2.0/attributes.yaml#/components/schemas/Person
        organization:
          $ref: https://schema.nfh.global/Organization/v2.0/attributes.yaml#/components/schemas/Organization
      required: []
      oneOf:
        - required:
            - person
        - required:
            - organization
      x-tags:
        - common
