openapi: 3.1.1
info:
  title: Ack
  version: 2.0.0
  description: "Container schemas fetched from beckn.yaml. This cannot be extended as it is a reserved schema in beckn protocol. Any additional properties added to this schema can only be made using its *Attributes property"
  license:
    name: CC-BY-NC-SA 4.0 International
  contact:
    name: Beckn Labs
    url: https://beckn.io
components:
  schemas:
    Ack:
      x-iri: https://schema.nfh.global/Ack/v2.0
      description: New v2.0 Ack format carrying an HTTP Counter-Signature proving
        the receiver authenticated, received, and processed the inbound request.
      type: object
      properties:
        status:
          type: string
          enum:
          - ACK
          - NACK
          description: ACK if the request was accepted; NACK if rejected.
        signature:
          $ref: https://schema.nfh.global/CounterSignature/v2.0/attributes.yaml#/components/schemas/CounterSignature
          description: Counter-signature proving the receiver authenticated and processed
            the inbound request.
      required:
      - status
      - signature
